version: '3'
services:
  build-stitcher:
    build:
      context: .
      dockerfile: build.Dockerfile
    container_name: build-stitcher
    volumes:
      - ../stitcher-data-inxight-clean:/opt/stitcher-data-inxight
    environment:
      - STITCHER_VERSION=1.3
    tty: true