version: '3'
services:
  get_updated_datafiles:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ../../stitcher-data-inxight-clean:/stitcher-data-inxight
      - ..:/stitcher
      - ./stitcher-build-logs:/stitcher-build-logs
    tty: true
    working_dir: /stitcher/workflows
