import os
os.environ["STITCHER_DATA_INXIGHT_DIRECTORY"] = "../stitcher-data-inxight"

rule ready_to_build_stitcher:
    input:
        "../stitcher-inputs/active/spl_summary.txt",
        "../stitcher-inputs/active/version_metadata.txt",
        "../stitcher-inputs/active/approvalYears.txt",
        "../stitcher-inputs/active/NCT_REPORT.txt.gz",
        "../stitcher-inputs/active/FDAanimalDrugs.txt",
        '../stitcher-inputs/active/FDAexcipients.txt'

rule download_daily_med_files:
    output:
        "../stitcher-inputs/temp/dm_spl_release_animal.zip",
        "../stitcher-inputs/temp/dm_spl_release_homeopathic.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part1.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part2.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part3.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part4.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part5.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part6.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part7.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part8.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part9.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part10.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_rx_part1.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_rx_part2.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_rx_part3.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_rx_part4.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_rx_part5.zip",
        "../stitcher-inputs/temp/dm_spl_release_remainder.zip",
        "../stitcher-inputs/temp/fda_initiated_inactive_ndcs_indexing_spl_files.zip"
    shell:
        "../scripts/dailymed/dailymed_get_noel.sh"

rule prepare_daily_med_summary:
    input:
        '../stitcher-inputs/temp/UNIIs.zip',
        "../stitcher-inputs/temp/dm_spl_release_animal.zip",
        "../stitcher-inputs/temp/dm_spl_release_homeopathic.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part1.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part2.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part3.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part4.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part5.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part6.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part7.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part8.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part9.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_otc_part10.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_rx_part1.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_rx_part2.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_rx_part3.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_rx_part4.zip",
        "../stitcher-inputs/temp/dm_spl_release_human_rx_part5.zip",
        "../stitcher-inputs/temp/dm_spl_release_remainder.zip",
        "../stitcher-inputs/temp/fda_initiated_inactive_ndcs_indexing_spl_files.zip"
    output:
        "../stitcher-inputs/active/spl_summary.txt"
    shell:
        "cd .. && scripts/dailymed/dailymed_prepare.sh stitcher-inputs/temp/"

rule run_approvalYears:
    input:
        '../stitcher-inputs/temp/UNIIs.zip',
        "../stitcher-inputs/active/spl_summary.txt"
    output:
        "../stitcher-inputs/active/version_metadata.txt",
        "../stitcher-inputs/active/approvalYears.txt"
    script:
        "../scripts/approvalYears.py"

rule download_clinical_trials_data:
    output:
        "../stitcher-inputs/temp/AllPublicXML.zip"
    shell:
        "curl 'https://classic.clinicaltrials.gov/AllPublicXML.zip' -o ../stitcher-inputs/temp/AllPublicXML.zip"

rule parse_clinical_trials_data:
    input:
        "../stitcher-inputs/usct-trial-to-substance-mapping-public-20210212.xlsx",
        "../stitcher-inputs/temp/AllPublicXML.zip"
    output:
        "../stitcher-inputs/temp/ctgovuniis.json.gz",
        "../stitcher-inputs/temp/ctdata.json.gz"
    script:
        "../scripts/clinicaltrials/index_clinical_trials.py"

rule download_clinical_trials_publications:
    output:
        "../stitcher-inputs/temp/pubmed/clinical_trials_downloads_are_complete.txt"
    script:
        "../scripts/clinicaltrials/grab_pubmed_trials.py"

rule download_asciimesh_files:
    output:
        "../stitcher-inputs/temp/c.bin",
        "../stitcher-inputs/temp/d.bin"
    shell:
        """curl 'https://nlmpubs.nlm.nih.gov/projects/mesh/MESH_FILES/asciimesh/c2024.bin' -o ../stitcher-inputs/temp/c.bin &&
        curl 'https://nlmpubs.nlm.nih.gov/projects/mesh/MESH_FILES/asciimesh/d2024.bin' -o ../stitcher-inputs/temp/d.bin"""



rule parse_pubmed_trial_papers:
    input:
        "../stitcher-inputs/temp/c.bin",
        "../stitcher-inputs/temp/d.bin",
        "../stitcher-inputs/temp/pubmed/clinical_trials_downloads_are_complete.txt"
    output:
        '../stitcher-inputs/temp/papers.json.gz'
    script:
        "../scripts/clinicaltrials/parse_pubmed_trial.py"

rule download_unii_data:
    output:
        '../stitcher-inputs/temp/UNII_data.zip',
        '../stitcher-inputs/temp/UNIIs.zip'
    shell:
        "curl -L 'https://precision.fda.gov/uniisearch/archive/latest/UNII_Data.zip' -o ../stitcher-inputs/temp/UNII_data.zip && "
        "curl -L 'https://precision.fda.gov/uniisearch/archive/latest/UNIIs.zip' -o ../stitcher-inputs/temp/UNIIs.zip"

rule compile_NCT_REPORT:
    input:
        '../stitcher-inputs/temp/papers.json.gz',
        "../stitcher-inputs/temp/ctgovuniis.json.gz",
        "../stitcher-inputs/temp/ctdata.json.gz",
        '../stitcher-inputs/temp/UNII_data.zip'
    output:
        "../stitcher-inputs/active/NCT_REPORT.txt.gz",
    script:
        "../scripts/clinicaltrials/compile_unii_nct_data.py"

rule download_animal_drugs_worksheets:
    output:
        "../stitcher-inputs/temp/Section12byApplicationNumber.xls",
        "../stitcher-inputs/temp/Section6VoluntaryWithdrawal.xls"
    shell:
        """curl --insecure -o ../stitcher-inputs/temp/Section12byApplicationNumber.xls 'https://animaldrugsatfda.fda.gov/adafda/app/search/public/tradeSponsorExcelByNadaAnada/Section12byApplicationNumber' &&
        curl --insecure -o ../stitcher-inputs/temp/Section6VoluntaryWithdrawal.xls 'https://animaldrugsatfda.fda.gov/adafda/app/search/public/voluntaryWithdrawalExcel/Section6VoluntaryWithdrawal'"""

rule scrape_nadas:
    input:
        "../stitcher-inputs/temp/Section12byApplicationNumber.xls",
        "../stitcher-inputs/temp/Section6VoluntaryWithdrawal.xls"
    output:
        "../stitcher-inputs/temp/NADAs.json"
    script:
        "../scripts/scrapeNADAs.py"

rule scrape_fda_animal_drugs:
    input:
        "../stitcher-inputs/temp/NADAs.json"
    output:
        "../stitcher-inputs/active/FDAanimalDrugs.txt"
    script:
        "../scripts/scrapeFDAAnimalDrugs.py"

rule scrape_fda_excipients:
    input:
        '../stitcher-inputs/temp/UNIIs.zip'
    output:
        '../stitcher-inputs/active/FDAexcipients.txt'
    script:
        "../scripts/scrapeFDAExcipients.py"